title: Einsatzfeld erkennen
difficulty: 1
question: |
  Welchem Einsatzfeld in der Produktion ist die Anwendung zuzuordnen?

  1. Eine Kamera erkennt fehlerhafte Schweißnähte.
  2. Ein System sagt voraus, wann ein Motor gewartet werden muss.
  3. Die benötigte Produktionsmenge für nächsten Monat wird prognostiziert.
tip: |
  Qualität, Instandhaltung, Planung?
solution: |
  1. Qualitätssicherung
  2. Instandhaltung (Predictive Maintenance)
  3. Produktionsplanung
